### ISSUE TITLE
Hay servidores a los que el Control Izquierdo + 1,2,3,4,5,6,7,8 no les va.-

### ISSUE THREAD

**Issue by Gameadictive** [matahombres/zz_taximeter#1]
Idear otro método estaría de 10.

**Comment by matahombres** [comment]
Mmm... Por lo que lo hice así es para evitar que el conductor tenga que utilizar el ratón para una interfaz tan sencilla
Una pregunta, tienes el script de baseevents activado o no? Porque a lo mejor es porque tienes la opción activada y no tienes el plugin.
También permites al usuario acceder a los botones directamente

**Comment by matahombres** [comment]
Se ha cambiado el método en #bc9f16b62fb253bd1dbf3cc87766ceb58dd6e21e

**Comment by matahombres** [comment]
Creado un nuevo método de selección para los botones en [#bc9f16b](https://github.com/matahombres/zz_taximeter/commit/bc9f16b62fb253bd1dbf3cc87766ceb58dd6e21e)
